export const actions = {
    TOGGLE_SIDEDRAWER: 'TOGGLE_SIDEDRAWER',
    TOGGLE_NESTED_NAV_DISPLAY: 'TOGGLE_NESTED_NAV_DISPLAY',
    STORE_PRODUCTS: 'STORE_PRODUCTS',
    TOOGLE_PRODUCT_CATEGORY: 'TOOGLE_PRODUCT_CATEGORY'
}